version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: user_service_postgres
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: user_service_redis
    ports:
      - "6379:6379"

  user-service:
    build: .
    container_name: user_service_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_REDIS_HOST: redis   # Change here
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:

