image:
  repository: user-service
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://c-user-service-demo.lrsb7vv5sz4c55.postgres.cosmos.azure.com:5432/user-service?user=citus&password=ctal@SS27&currentSchema=user_service_schema&sslmode=require
  SPRING_DATASOURCE_USERNAME: citus
  SPRING_DATASOURCE_PASSWORD: ctal@SS27
  SPRING_REDIS_HOST: redis
  SPRING_REDIS_PORT: 6379
  SPRING_PROFILES_ACTIVE: docker
  APPLICATIONINSIGHTS_CONNECTION_STRING: InstrumentationKey=0a1d90f5-c5cd-4f7a-9229-4a9e9cc45997;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=d052c407-2f75-4a8a-9694-ea255fc7e626
