apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: userservice.localhost
      http:
        paths:
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: user-service  # Update to match the service name
                port:
                  number: 8080
